name: 提交 Bug
description: 在使用 本网站 过程中遇到了问题
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🩵 | 感谢你愿意提交 Bug 报告
        ## ❗ | 请确定没有相同问题的 Issue 已被提出。
        ## 🌎 | 请准确填写环境信息。
        ## ✍️ | 为了避免无效 Issue 占用你我的时间，请按真实情况填写下方表单，谢谢。
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经按照教程文档正确使用本网站，问题依旧存在。"
          required: true
        - label: "我已经在 [Issue Tracker](https://github.com/adproqwq/GKD_sub_share/issues) 中找过我要提出的问题，没有找到相同问题的 Issue。"
          required: true

  - type: markdown
    attributes:
      value: |
        ## 环境信息

  - type: dropdown
    id: env-vm
    attributes:
      label: 系统
      description: 选择系统
      options:
        - Windows
        - Android
        - iOS
        - 其它（在下方补充说明处另外说明）
    validations:
      required: true

  - type: dropdown
    id: env-browser
    attributes:
      label: 浏览器
      description: 选择浏览器
      options:
        - Windows Edge
        - Chrome
        - Safari
        - 其它（在下方补充说明处另外说明）
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        我们需要执行哪些操作才能让 Bug 出现？
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际的结果是什么？需要附上报错截图，否则将关闭。
    validations:
      required: true

  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）
